language:
  cpp

compiler:
  g++

install:
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake

script:
  - pwd
  - ls
  - cd /usr/src/gtest
  - pwd
  - ls
  - sudo cmake CMakeLists.txt
  - sudo make
  - ls
  - sudo cp *.a /usr/lib
  - cd
  - ls
  - make test
