language:
  cpp

sudo:
  required

dist:
  trusty

addons:
  apt:
    packages:
      - libusb-1.0-0-dev

compiler:
  g++-6

install:
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake

script:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd /home/travis/build/University-of-Utah-CS3505/a4-testing-and-travis-fall-2018-gurpartb
  - make test
